### PR TITLE
Prep for CRAN release

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

Addressing all the little annoying things CRAN will want. That includes skipping the testthat tests that need credentials (because those won't work on CRAN).

### CODE REVIEW

**Comment by cansavvy** [comment]
@howardbaek This isn't *quite* ready for review. the `skip_on_cran()` isn't working as I need it to. 

Any idea on how to make the testthat tests NOT run on CRAN but STILL run on GitHub actions? I see various solutions online but so far they aren't working.

**Comment by cansavvy** [comment]
I think I fixed it by getting rid of the `--as_cran` flag, but if you wanna double check, that sounds good.

**Comment by howardbaek** [comment]
I was able to run through all tests locally:

Screenshot 2024-01-24 at 4 34 28 PM

What exactly is the problem here? If you can elaborate, I can look into it. I have experience submitting an API wrapper to CRAN with [conrad](https://github.com/fhdsl/conrad).

**Comment by cansavvy** [comment]
Sorry, forgot to leave a comment to update: but I believe everything is squared away. But if you'd like to check over this PR and see if you agree with the strategy, that'd be great!

**Pull request merged**
